# Generated by Django 3.1.4 on 2020-12-05 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF/CNPJ')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
    ]
